apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-ops
  namespace: monitoring
spec:
  dnsNames:
    - '*.ops.netsoc.ie'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-ops
