apiVersion: v1
kind: ConfigMap
metadata:
  name: kubelan
  namespace: webspaces
data:
  kubelan.yaml: |
    log_level: DEBUG
    services:
      - dnsmasq
      - lxd8s
      - webspaced
      - kube-system/traefik
    vxlan:
      interface: lxd-overlay
      vni: 7331
