---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: element-web
  namespace: matrix
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: semver:~1.7
spec:
  chart:
    repository: https://ananace.gitlab.io/charts/
    name: element-web
    version: 1.0.5
  values:
    image:
      repository: vectorim/riot-web
      tag: v1.7.8

    defaultServer:
      url: https://matrix.netsoc.ie
      name: netsoc.ie
      identity_server: https://matrix.netsoc.ie

    config:
      disable_custom_urls: true
      disable_guests: true
      disable_3pid_login: false

      brand: Netsoc
      branding:
        welcomeBackgroundUrl: 'https://www.netsoc.ie/assets/images/matrix/bg.svg'
        autoHeaderLogoUrl: 'https://www.netsoc.ie/assets/images/matrix/logo.png'

      welcomeUserId: ''
      defaultCountryCode: IE
      showLabsSettings: true

    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts: [matrix.netsoc.ie]
      tls:
      - secretName: tls-main
        hosts: [matrix.netsoc.ie]
