
apiVersion: v1
kind: Secret
metadata:
  name: accounts-secrets
  namespace: default
data:
  values.yaml: YmFja2VuZDoKICBzZWNyZXRzOgogICAgc3RyaXBlUHJpdmF0ZUtleTogc2tfdGVzdF81MUhVQ2JmSTIyelVyQTdxOEh1RXV6cVc1QU5HT0E0WnpiUHM0NXBjUGRMNHlEbjd0VHlEb2ppVVFzekNBbDcwaTZGUDU1Y1RvN3VxSmtpSjE0U29zdmNsYTAwQldZSFdXTWcKICAgIHN0cmlwZUVuZHBvaW50U2VjcmV0OiB3aHNlY19YUWVUNmJwZnFjQXlXM3l0UGhuSE9ZUU50Vkc1MkxSMwo=
