apiVersion: v1
kind: Secret
metadata:
    name: accounts-secrets
    namespace: default
data:
    values.yaml: ENC[AES256_GCM,data:AcyGtR8KV672tpnCiQ4EnfrX9XvF1Fz27+GfQxZbqVoIcodLjUlHg/2ZuVBEAYEzyu121iQhLF9e/yXOBZ6ppQdIUhr7Aaix/oEjSQNJPx8JUi8e5V+jSeaEyS1BL4gcnOeb67zXtsOY7Lerz/O+VjxFEfFxiGn3m4bb0oPdL7eRF5m7/xWEF8r9qZ6UYhe251Q9WI2gEf8P9TzpF5/pRwSFEVqZynBRiTv6VkQRoGjGLcGK2qSya+JIbN6M6+GUpy1qSJlRfVo1lyc6RIqmgqsyBool4XZ2pZK3K9xIk1I1IhSrlAj9VYAvtMJdUhlMaTc/jCH3UdFX3e+itPJmChQ/DQmX3oWclc6fKo8gj7dBykUV2nYKJ0svMhVRGnUD,iv:8SBOCQCxbu9aXFL5jEWFLtO0U1UnBxwtXO5jFOD2eX0=,tag:+gtXEiSFTHMvcP0/SvMo+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-27T18:43:47Z'
    mac: ENC[AES256_GCM,data:KcSueHWKf1dL43ScTmQLr1Td/gfu0Rip3EX1ckhTEF/CdsKvvn1XNtmOSxpIHL9Xa+ablVk53NqvcxEgmg87V/7I+P8WvKgBhD5TcCaF0BUvhtR61lYM81Sr/YS/D4it2ax2FkNMS/NBes5NMitr2R3AFK4Y9d+ap40OebneHG0=,iv:QW4baJxRM0BlC7Sn9xnVwYDVqK8yloKxU5pPzoyT37w=,tag:oXW3xnNLQC0If4fG3H/ahw==,type:str]
    pgp:
    -   created_at: '2020-09-27T18:36:40Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv8DePk5hRFiMf5yETNRG4A++VcXQuSGxgnQmqJmx9kjmBf
            vxove74hJUX3kN/2Z1yfDMKCnWhmHTnIcfd9NubFJKQKMQ+xk7oQwS1eRfSnjVhG
            wL2AJYAahjDOXZW6gOihR1poK/LtrULOo5mTzhmWnXpQnFtiridNSJxJYL1Hi8fC
            P1gU2FgfIxrk6lQv+45NJiAYqmeMlxqKdGwuRMFi9qnHCov5/UaenmYYtWWbNSky
            9ujWRjKlKyvUu6ZzkLKZAgFdawWl/RaV4XJ9OCIM0YSCx7eXbHNXEHtMuicD99Ql
            wCAvmqxdpmTbxxeYmJIVArexckXhhMXsuJCoYVlx4d5ebRwSNezjlDST2r799yUq
            FiSsCstc6KS+FQ3CGQsiiiueyXgQjBLlsih1eV1MvclWY8NtWxPHMaP18P1/oN2V
            UIXz7hlYVRYj3WVf3X7GQNzDqEQ/vHn3KQK8t8TD8RVma9L3bB0pIDcEYfdCfQxq
            DPdMK4qCG0sjmJQnvEIt0lwBS7iNhh/3U4wU/L4epG7dZbmig6vJVbvDFXh2w5St
            2zUaKVj03izVqGuAgGXR780b1EqY587MvJ5NgSpTev54F5V2I1xfN4DZkLBJ1jdb
            pvfW4pIrT1CkX7PzsQ==
            =M9d2
            -----END PGP MESSAGE-----
        fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: ^data$
    version: 3.6.0
