---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: accounts
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/frontend: semver:~0.1
    filter.fluxcd.io/backend: semver:~0.1
spec:
  chart:
    repository: https://netsoc.github.io/charts/
    name: accounts
    version: 0.1.4
  values:
    ingress:
      enabled: true
      tls:
      - hosts: [accounts.netsoc.ie]
        secretName: tls-main
      hosts: [accounts.netsoc.ie]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'

    frontend:
      image:
        repository: ghcr.io/netsoc/accounts/frontend
        tag: '0.1.4'
      config:
        IAM_BASE_URL: 'https://iam.netsoc.ie/v1'
        PAYMENT_BASE_URL: https://accounts.netsoc.ie/api
        STRIPE_PUBLIC_KEY: 'pk_live_514gI43BPJxpSdBx8CBrEF4fsRfeqFvKvVEXovndX3QnR4eYnELroykjvTRsZ2RXJXFr62MYgfMrrEmVInV4jho75004xyHQLCT'
        MAIN_WEBSITE_URL: 'https://www.netsoc.ie/services/'

    backend:
      image:
        repository: ghcr.io/netsoc/accounts/backend
        tag: '0.1.4'
      config:
        ACCOUNTS_BASE_URL: https://accounts.netsoc.ie
        IAM_BASE_URL: http://default-iamd/v1
  valuesFrom:
  - secretKeyRef:
      name: accounts-secrets
