---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docs
  namespace: default
  annotations:
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: https://netsoc.github.io/charts/
    name: docs
    version: 0.1.0
  values:
    image:
      repository: ghcr.io/netsoc/docs
      tag: 990f5c42fa9772dd91b26fbd10f049d6fb9b9b2b
    replicaCount: 1
    ingress:
      enabled: true
      tls:
      - hosts: [docs.netsoc.ie]
        secretName: tls-main
      hosts:
      - host: docs.netsoc.ie
        paths: [/]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
