apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
    name: iamd
    namespace: default
    annotations:
        fluxcd.io/automated: "true"
        filter.fluxcd.io/chart-image: semver:~0.1
spec:
    chart:
        repository: https://netsoc.github.io/charts/
        name: iamd
        version: 0.1.3
    values:
        image:
            repository: ghcr.io/netsoc/iamd
            tag: latest
        replicaCount: 1
        ingress:
            enabled: true
            tls:
            -   hosts:
                - iam.staging.netsoc.ie
                secretName: tls-main
            hosts:
            -   host: iam.staging.netsoc.ie
                paths:
                - /
            annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
        config:
            log_level: DEBUG
            mail:
                from: '"Netsoc IAM" <iamd@mg.netsoc.ie>'
                reply_to: '"Netsoc suppourt" <support@netsoc.ie>'
                verify_url: https://accounts.staging.netsoc.ie/verify?token={{.Token}}
                reset_url: https://accounts.staging.netsoc.ie/reset?token={{.Token}}
                smtp:
                    host: smtp.eu.mailgun.org
                    port: 587
                    username: iamd@mg.netsoc.ie
                    tls: true
            jwt:
                issuer: netsoc
                login_validity: 8760h
                email_validity: 24h
        postgresql:
            enabled: true
            postgresqlPassword: ENC[AES256_GCM,data:1yXooQSkO6+3W/K7SufmSA==,iv:XA+EXWNWbLVYnowOEB4hVMgjttJ1tcr0Wca7jdSrbdY=,tag:gE/7PI9Icf8tIYgkAslrRQ==,type:str]
        secrets:
            smtpPassword: ENC[AES256_GCM,data:PUwsToNijrIjIxiRdGrJZZU4i5QxrVpcxXj+mWuTuaQTsGmrROw0pfPNyOByQaxmb8E=,iv:gJPshQ8vhmuX+cMaEwS2ALGruD3qgl/IYXEvACtLyV0=,tag:kZMKgjSRbp/1rhyNcowwAg==,type:str]
            jwtKey: ENC[AES256_GCM,data:Jzh4z099JcjdSSr1d88mpIyr9pp+FWKok2OUdHueXZ9EXOJThDH3MNnMIA0=,iv:2ZV08VJK2I6LrCOL+vrsBSSkiJFZhzwoH/cafzwdCpg=,tag:MTB5+bWpBqFkwgSml0kdnQ==,type:str]
            rootPassword: ENC[AES256_GCM,data:yMA8kqH7eKqbkx74ZRKFpA==,iv:mF/di3sDOL5HpiuUzG/DuiaLAoa//FApaS+cAhdQ2Vc=,tag:htl3PUm8K7Z4ZzeMssKZMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-21T18:04:37Z'
    mac: ENC[AES256_GCM,data:+zujshAqoseN8/7QlMJWKgHVGZhaXJ8bB9uOQbWVxluTm9G30d1PoM3TPxRmDz06QS+Np9eE3fd7N7/HG95+sm0/Hpvawndvx/SSB3cLxwbhI+jp2Q8wST9hNVFWD/96ik3SvM9CuL/yTJXCzzUO5ic6nbhmwethdg8w5kWBl9k=,iv:5pG+zM5W2juscJ58QWUCHTli6bqAgWPQ/P/M/jEqbJA=,tag:LKEzeho+hEaQDdTjoFmrKA==,type:str]
    pgp:
    -   created_at: '2020-09-21T17:55:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQv7BVkJ8TXrjoZ0rqm1csate3ItStgHpHM167Bfhay5OOrF
            b6hBF357x52COwtGM8lG+OkvXXA7Xx0zRh9sKpDBaPzB/+K3fkM6KHhZPas4JEej
            SBoUMvXP6ALRtCnmrR+SIw5GsnkoGQm/9bnxDCqmO2dH3x5EYa5vOiNtVqd3LePD
            yJmwxqODQybH6ntUOX8nMcPgDldOA51CHNBAe6AetrL5mZvJJUuKnEKJzfnI0YB2
            EAGC4/r7y1MiSO5DG9Xhw7Gcvgm2VLm2gpoEo14iDTgRieFsX0Bl7HVsQz5vz0TZ
            rFnOH48tNtIuj6nCkweBDLDQ1/06lsco7+jPkzqIm4O63k/09szR0tKXBki2CJq1
            m0owRpNUYsuTTQezLiv+dOedzX4z01FktUmEV72M2HHLn+jpv6T0gKs2z15ytzLj
            b/NQ6FB7h3PwfTUjqPzVb50G5dJ7xrcIow0OxZWGGVnYdpS2yuKTa6U60DA9Mi4j
            cgq4ZdOGvWT4WBIZB/yg0l4BQpxj7OJLlP5BqymdKkWdu4K7SPp3cDzOMm7mSK0i
            ueaYk6FrFCoyFWCmf5MOgteMvd6R8OGEbGpgFkESMLHyXVUpJeiNHjkknPWsN5gO
            xZpGQLmo7GJvtI3ghWxx
            =DJ1d
            -----END PGP MESSAGE-----
        fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: ^(.+Password|secrets)$
    version: 3.6.0
