---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 5.0.0
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 5.0.0
    replicaCount: 1
    ingress:
      enabled: true
      tls:
      - hosts: [podinfo.ops.staging.netsoc.ie]
        path: /
        secretName: tls-ops
      hosts: [podinfo.ops.staging.netsoc.ie]
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
