---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: shhd
  namespace: default
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: semver:~0.1
spec:
  chart:
    repository: https://netsoc.github.io/charts/
    name: shhd
    version: 0.1.3
  values:
    image:
      repository: ghcr.io/netsoc/shhd
      tag: 0.1.1

    config:
      iam:
        url: 'http://default-iamd.default/v1'

  valuesFrom:
  - secretKeyRef:
      name: shhd-secrets
