---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: website
  namespace: default
  annotations:
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: https://netsoc.github.io/charts/
    name: website
    version: 0.1.0
  values:
    image:
      repository: ghcr.io/netsoc/website
      tag: e508aa0af5338c1a78daf5532a72ab43ceaf1e92
    replicaCount: 1
    ingress:
      enabled: true
      tls:
      - hosts: [www.staging.netsoc.ie]
        secretName: tls-main
      hosts:
      - host: www.staging.netsoc.ie
        paths: [/]
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
  namespace: default
spec:
  redirectRegex:
    regex: '^https://staging.netsoc.ie/(.*)'
    replacement: 'https://www.staging.netsoc.ie/${1}'
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: www-redirect
  namespace: default
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`staging.netsoc.ie`)
    kind: Rule
    services:
    - name: noop@internal
      kind: TraefikService
    middlewares:
    - name: www-redirect
      namespace: default
  tls:
    secretName: tls-main
    domains:
    - main: 'staging.netsoc.ie'
      sans:
      - '*.staging.netsoc.ie'
