---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: website
  namespace: default
  annotations:
    fluxcd.io/automated: 'true'
spec:
  chart:
    repository: https://netsoc.github.io/charts/
    name: website
    version: 0.1.0
  values:
    image:
      repository: ghcr.io/netsoc/website
      tag: 0eb5c04a7c1e69065c404d11aa825fbb63a8f4ee
    replicaCount: 1
    ingress:
      enabled: true
      tls:
        - hosts: [www.staging.netsoc.ie]
          secretName: tls-main
      hosts:
      - host: www.staging.netsoc.ie
        paths: [/]
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.middlewares: default-www-redirect@kubernetescrd
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
  namespace: default
spec:
  redirectRegex:
    regex: '^https://staging.netsoc.ie/(.*)'
    replacement: 'https://www.staging.netsoc.ie/${1}'
