apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-main
  namespace: default
spec:
  dnsNames:
    - 'netsoc.ie'
    - '*.netsoc.ie'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-main
