apiVersion: v1
kind: Secret
metadata:
    name: zammad
    namespace: support
data:
    values.yaml: ENC[AES256_GCM,data:4wGHjPFhgvCHmGdxJ9iInuzSP5UMDeWDADDFCEM8FGn11gT3AXy7ms8qohCMafGkcpQTzGGDMU8Hr2Ewcs+JVwF97X2R0oc05ONGIPFmk3qSZoRQ02a94CqiA/83Aekd0vb9BdES0zo6wb9cW4hDeWyvydk5OXRihASWKqKmXJBl3vz1r3ENYAvdsxI=,iv:SQDjWJvOE0TYtEaM9OloqB5atCK/LjLLBvY9qulfI6Q=,tag:bBGc+YUmhZ0197SBQ/nlAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T17:11:36Z'
    mac: ENC[AES256_GCM,data:peSX0V+3zSRZaGqCypPiECISwSA+Ral5fNEar7XrZUL3NNd6uQOL+x8CdyUnVi12Sud9Zx0tdw5K/JtpOZsz9Ggv6tIgaQbXghJ7xba33MQXL254gt3rfQTa84o4QuCJiX0AuzYbbYF8AGe94bxEy2GErMwoqDEBrBZZ3i5mzLU=,iv:WopwRJ6ilVtUFTUrDzc5mku+3oK9XiiTk/xqBoRwDnw=,tag:/GYaxsQG8KAJ6y3dInJWZQ==,type:str]
    pgp:
    -   created_at: '2020-09-30T17:11:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQwAnS7yO3j/is1LD11Y4a1DRQMXWnu2refk/ZtljN1xHEzE
            VUcc0kngWYtquvlisvx6NUx5pnd4c/XrL9ZlGf/IwtUM4nWSBMsxfZXybxwxvcUZ
            1w+JKjyo7BpESblWG6+WWAK0pGVi5z/p2dX9O8P19V2HDGIfJK7rfha4gDrD8+64
            rZcVoQFxKLDMZpKJxFRt3/HlrqCAWsI4XNBFkRT7RdFGkWj5wJUNX+wIs4nCQVDX
            SUa9PzIXiG6f7pJHs365cpVdkSuh+uPFwZYBtvnhFVoC789DEg7sShmdljTZ5WUA
            aWSfhyJvWSmHIpCiSErc+jzbQGY7QO6qzQNqr5q8WODTx/CI525dDbmhJWmiC24r
            Vb/RND8rDO6WvfyhFonQp7ZVi4ximlBGPJMDp9tdO/+RCFVc36BsabMqOY5n7l37
            WnAiz6+dgWscLwiI+3s4GIiLFR8kM9Ygl0FVYf/0GyCU2G8Zy4e5mda8XUtxULYb
            8xb1+5zZh0wiuecd/uU90l4BJVFbMwE1aKhmvvn3+TmAv7U3vhdzLh/BG5/Nf34J
            v3j37THOZTHmYTAJCRWCk8Q+DJWJ4IZ3FD7OMmev9cD+3XZ7GBwWmUVrxMJfg7rX
            ToGuftwyLytlA4iQrN3y
            =kIMi
            -----END PGP MESSAGE-----
        fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: ^data$
    version: 3.6.0
