---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v1.0.1
  values:
    extraArgs:
      - '--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53'
