apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    email: internet@csc.tcd.ie
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        rfc2136:
          nameserver: cube.netsoc.ie
          tsigKeyName: 'staging.netsoc.ie.'
          tsigAlgorithm: HMACSHA512
          tsigSecretSecretRef:
            name: cubedns-tsig
            key: k8s.key
