---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-ops
  namespace: kube-system
spec:
  dnsNames:
  - '*.ops.staging.netsoc.ie'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-ops
