apiVersion: v1
kind: Secret
metadata:
    name: traefik-ops-users
    namespace: kube-system
data:
    users: ENC[AES256_GCM,data:K+ZwlOTQ9OeWT5L9RqkAd85XEhcBeiaB2LA/vghy8oH/W/BiuYsta4e+gDsytqAfqeZ6l9WjmFM=,iv:Uz+zHVTtmCllOvGlwdDM/on9kMhDQFWKZT6VuDdqk80=,tag:KNQcvaPX3Jy0M7mgVSgIRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-20T21:28:21Z'
    mac: ENC[AES256_GCM,data:FfkmdE97bQX43p2R9pl0X3hECf2ZZbu/CqqPyL3WrM/VODInqrFrIlBzGuNomf93DMClhumloNaGy2WtCEZJ7bblKsPFkIQ8cZZC8T5epzvr5e6np8D6t3Om0snjcCxFrzP7a+JxIYEEVzYQXAS/0+YQm3CZ/L8HRAg6Kv6rQZ4=,iv:f0YH7fPQbh9NXr+2ZmKkJk/DAklOSKyjJdM+CFp10/c=,tag:sNaQtKFIHbmUXUVxmE2+bw==,type:str]
    pgp:
    -   created_at: '2020-09-20T21:28:21Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA5AfX+B6AMX7AQwAln13qevRL7TtBYo8N4EvFK7IlirjPv9jp3JNXILYKTzF
            Xb20PWwwGES2nGNgrgWvKO3bCh+5Zk5tfLM41Ov7RiE1e/v2rHuadt2jm3Yte4kV
            gwR6SxcN0C4GCr+demX/wHFUkMtGtDoTylRZObhk1Hc5J5a9M9mm4ZzIUT/P6qWF
            ARoan0sszCqlJRCKFgUmWm6rER6TxTfEvyYn9lRO12eD+e3iNd0sqfIxYRa4HTzD
            /7NmtpTpnWbbVjKj0CgzYsaaBXc/qiROIZ0/tVBF+YMCyiA5dMZHrDdTu2JsblYp
            M2RB0reifRtUluAVvHLH9xQoQPnNX3ee/5MNuvcpweCDkwk9TOlMyIVKwqOPHFnV
            xt9ufW5uiQb1gUai7XZL7ZAssYbsw7JBA9qApfov0gPS27GMqxjvdCyByhTG6ozx
            zLztpukVtFyJgOFdoncQXM5+jf6CirP+aumRJRm8sxXAxaVY//8aPNPz1iDEjj8y
            NrMgJl5bXCZLLNwH6m0/0l4BKAyXW+m+ZuTybOdDTo1GQTwyCiudXQHyr0sqP512
            B1E80O9iBPmD5ezBUL9sXf8jJ8RH0OhU5hYBag/WL3X3vfRNIve55nhhRQeo9IgE
            ISZCgjFRy28f98Umj3W6
            =uhfA
            -----END PGP MESSAGE-----
        fp: DB2E28B13D53C8DD62FE560B408F6E592A12DF74
    encrypted_regex: ^data$
    version: 3.6.0
