---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/automated: 'true'
    repository.fluxcd.io/traefik: image.name
    tag.fluxcd.io/traefik: image.tag
    filter.fluxcd.io/traefik: glob:2.3.*
spec:
  releaseName: traefik
  helmVersion: v3
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    image:
      name: ghcr.io/netsoc/traefik
      tag: 2.3.0-9bd3fc3f
    deployment:
      replicas: 1
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetes:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        protocol: TCP
        port: 8080
        expose: true
        exposedPort: 80
        redirectTo: websecure
      websecure:
        protocol: TCP
        port: 8443
        expose: true
        exposedPort: 443
    service:
      enabled: true
      type: LoadBalancer
    ingressRoute:
      dashboard:
        enabled: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints: [websecure]
  routes:
  - match: Host(`traefik.ops.netsoc.ie`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
    - name: auth
  tls:
    secretName: tls-ops
    domains:
    - main: '*.ops.netsoc.ie'
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kube-system
spec:
  basicAuth:
    secret: traefik-ops-users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: dashboard-redirect
  namespace: kube-system
spec:
  redirectRegex:
    regex: '^https://traefik.ops.netsoc.ie/(.*)'
    replacement: 'https://traefik.ops.netsoc.ie/dashboard/${1}'
    permanent: true
