---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  helmVersion: v3
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: 1.0.2
  values:
    persistence:
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      host: longhorn.ops.staging.netsoc.ie
      path: '/'
      tls: true
      tlsSecret: tls-ops
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: >-
          longhorn-system-force-forwarded-https@kubernetescrd,kube-system-auth@kubernetescrd
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-retain
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: 1
  staleReplicaTimeout: "30"
  fromBackup: ''
  baseImage: ''
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: force-forwarded-https
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      # This seems to be required due to some weirdness with Traefik and Rancher stuff
      X-Forwarded-Proto: "https"
